{{- if .Values.konga_node_seed -}}
apiVersion: v1
stringData:
  kong_node.data: |
    module.exports = [
{{- with .Values.konga_node_seed }}
      {
        "name": "{{ .name }}",
        "type": "{{ .type }}",
        "kong_admin_url": "{{ .kong_admin_url }}",
        "health_checks": {{ .health_checks }},
        "active": {{ .active }},
      }
{{- end }}
    ]
kind: Secret
metadata:
  name: {{ include "konga.fullname" . }}-node-seed
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
