apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "application.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  name: {{ include "application.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'false'
        timestamp: "{{ .Values.timestamp }}"
      labels:
        deployment: {{ .Chart.Name }}
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "application.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          tcpSocket:
            port: {{ .Values.service.port }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
