replicaCount: 2
image:
  repository: 663293147050.dkr.ecr.us-east-1.amazonaws.com/rumo-mservices-dev/devportal
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: 0.1
    memory: 20Mi
namespace: "api"
metrics:
  type: ClusterIP
  port: 9113
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/app-root: /devportal/catalog/
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "16k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      expires -1;
  hosts:
  - host: "devportal-dev.ti.devtirumo.net"
    paths:
    - "/"
nodeSelector: {}
tolerations: {}
affinity: {}
apiSpecsGitRepository: "https://bitbucket.org/rumo_logistica/devportal-specs-eks.git"
apiSpecsBranchName: "prisma-stack-microservicos-qas"
apiSpecsSyncInterval: "180"
oauthproxy:
  enabled: true
  configSecret: devportal-oauthproxy-config
  port: 8081
