apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: devportal
              servicePort: web
        {{- end }}
  {{- end }}