apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get