apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "application.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ include "application.fullname" . }}