apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-api-specs-access-devportal
  annotations:
    fluxcd.io/automated: "false"
  labels:
    {{- include "application.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: bGVvbmFyZG9ocGVyZWlyYQ==
  password: SEpOalJZVktUYzlyVk5XVlB3d2U=
