apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "application.fullname" . }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: devportal.{{ .Values.namespace }}.svc
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if not .Values.oauthproxy.enabled }}
    - port: {{ .Values.service.port }}
      name: web
    {{- end }}
    {{- if .Values.oauthproxy.enabled }}
    - port: {{ .Values.oauthproxy.port }}
      name: web
    {{- end }}
  selector:
    app: {{ .Chart.Name }}
