apiVersion: v1
version: 1.0.0
appVersion: 1.0.0
name: konga
engine: gotpl
description: A Helm chart for Konga
home: https://github.com/pantsel/konga
maintainers:
- email: 3bit.techs@gmail.com
  name: 3bit.techs
sources:
- https://github.com/pantsel/konga
keywords:
  - konga
  - kong
  - postgresql
