{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluent-bit-aws.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluent-bit-aws.name" . }}
    helm.sh/chart: {{ include "fluent-bit-aws.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.rbac.serviceAccountAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end -}}  
{{- end -}}